### PR TITLE
Media Restyle Folder section

### PR DESCRIPTION
**Pull request by liviu-preda-tsystems**
https://jira.telekom.de/browse/NMC-2578
image

### CODE REVIEW

**Comment by tsdicloud** [comment]
When looking closer to the customisations, I found an inconsistency behind the scenes:
The css customisation is done in a `css/apps/media.scss`, but there is no app called "media".
The app name is photos, although customer and designer always used "media".
The naming also interferes with @media queries, so it is not obvious to search for the photos customisations in media.

Even if it is uncomfortable, I would rename media.scss to photos.scss for consistency and more intuitive code structure.

**Review by tsdicloud — DISMISSED** [review]
Please rename style.

**Comment by aleksei-nmc** [comment]
label should be bold and black, text shadow should be removed
gap between label and icon should be 16px
Screenshot 2023-11-17 150636

**Comment by aleksei-nmc** [comment]
icon with label shouldn't disappear when hovered over
Screenshot 2023-11-17 151323

**Review by aleksei-nmc — CHANGES_REQUESTED** [review]
please fix the style issues

**Comment by liviu-preda-tsystems** [comment]
> When looking closer to the customisations, I found an inconsistency behind the scenes: The css customisation is done in a `css/apps/media.scss`, but there is no app called "media". The app name is photos, although customer and designer always used "media". The naming also interferes with @media queries, so it is not obvious to search for the photos customisations in media.
> 
> Even if it is uncomfortable, I would rename media.scss to photos.scss for consistency and more intuitive code structure.

Fixed

**Comment by liviu-preda-tsystems** [comment]
> icon with label shouldn't disappear when hovered over Screenshot 2023-11-17 151323

Fixed

**Comment by liviu-preda-tsystems** [comment]
> label should be bold and black, text shadow should be removed gap between label and icon should be 16px Screenshot 2023-11-17 150636

On my side it looks just like in the attached screenshot from my initial PR comment. we can see in the CSS changes also that the text is black, bold and text shadow has been removed. I have added a gap of 16px now as suggested.

**Review by aleksei-nmc — APPROVED** [review]

**Pull request merged**
